### ISSUE TITLE
trouble starting up server

### ISSUE THREAD

**Issue by Skywalker646** [SWG-Source/swg-main#5]
i set everything up but when i try to run the server, i get 2 messages. 

./startServer.sh line 23: 1472 illegal instruction   ./bin/loginserver -- @servercommon.cfg
./startServer.sh line 25: 1478 illegal instruction   ./bin/TaskManager -- @servercommon.cfg

any idea how i can resolve this?

**Comment by Cekis** [comment]
How is this a bug?!?  Your best bet to get help like this is in the discord channel.

**Comment by Tekaoh** [comment]
@Skywalker646 Recompile your src.

For the benefit of anyone who finds this via Google search or something someday, those errors happen when you're trying to run the server with a CPU that has a different instruction set than the one that compiled the code. The solution is to recompile the src with the CPU that you intend to use to run it.
