### ISSUE TITLE
Guide on Multi-Machine Hosting For PlanetServers

### ISSUE THREAD

**Issue by GeneUNCG** [SWG-Source/swg-main#7]
There should be a guide that describes on how to split up the GameServers and PlanetServers between two or more machines.

**Comment by rohvani** [comment]
Perhaps you could experiment with this a bit? As far as I’m aware, no one in the swg source project, aside from those involved with legends, have done much with this. Elour would be a good person to ask, I think.

**Comment by GeneUNCG** [comment]
Doodle and I have played around with it for a few days and nothing worked unfortunately. I was only able to get the LoginServer and LogServer separated (those are pretty straight forward, just set the correct IPs in the configs).

**Comment by Tekaoh** [comment]
I think this is a little bit outside the scope of the project. If someone gets around to it, cool. But for now, I'm just going to close it out as an issue.
